# Generated by Django 4.1.5 on 2023-01-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_note_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="user",
        ),
    ]
