
# Generated by Django 4.1.5 on 2023-01-05 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=127)),
                (
                    "time_course",
                    models.CharField(
                        choices=[("AM", "Am"), ("PM", "Pm")], max_length=20
                    ),
                ),
                ("schedule_time", models.CharField(max_length=20)),
                ("schedule_date", models.CharField(max_length=20)),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Baixa", "Baixa"),
                            ("Média", "Media"),
                            ("Alta", "Alta"),
                        ],
                        default="Baixa",
                        max_length=20,
                    ),
                ),
                ("guests", models.CharField(max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Lazer", "Lazer"),
                            ("Trabalho", "Trabalho"),
                            ("Reunião", "Reuniao"),
                            ("Família", "Familia"),
                            ("Projetos", "Projetos"),
                            ("Esportes", "Esportes"),
                            ("Tarefas", "Tarefas"),
                            ("Saúde", "Saude"),
                            ("Festas", "Festas"),
                        ],
                        default="Tarefas",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
