# Generated by Django 4.1.5 on 2023-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_task_guests"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="guests",
            field=models.CharField(default=["teste@gmail.com"], max_length=500),
            preserve_default=False,
        ),
    ]
